Feature/app (#12)
* init

* versions

* migrate yew app

* use spin 3

* Revert "use spin 3"

This reverts commit 116a7d6aa2117da3f0b2b478be49bf66b9912c01.

* titles, fixes

* wip: add rive

* add rive

* stepper animations and fixes

* feat worksheet tabs

* feat description, layout improvements

* feat worksheet dummy

* feat: plain an list input

* 🏗 solution form

* 🏗 form signal macros

* feat: privacy notice and worksheets storage

* split  macro files

* 🏗 form xp: undo remove, defaults

todo:
- panicked at /Users/anvlkv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.6.11/src/runtime.rs:838:30:
called `Result::unwrap()` on an `Err` value: OwnerDisposed(Owner(NodeId(261v1)))

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3000/pkg/a_nvlkv_xyz.js:533:13
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[2147]:0x1256a3
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[1123]:0xed8d8
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[1677]:0x1157cc
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[1389]:0x10902c
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[987]:0xdf3b1
@http://localhost:3000/pkg/a_nvlkv_xyz.wasm:wasm-function[1828]:0x1218c6

* 🏗 form improvements

* feat: form

* 🏗 xata db

* 🏗  get examples, set steps sequence

* 🏗 use error boundary, stepper layout

* layout fixes

* feat dark mode toggle

* 🏗 examples and steps

* feat: svg icons

* feat: rive component

* update: icons

* 🏗 pages

* 🏗 case view

* 🏗 case view and dummy

* inquire, improvements, split localizations

* 🏗 process CTA button and actions

* 🏗 inquire

* layout fixes, inquire

* 🏗 printing worksheets

* print wk layout

* fixes and improvements

* feat: cv page

* 🏗 translations and improvements

* feat: tracking

* update readme

* mv tracking

* feat: darg-orderable lists

* minor improvements

* generate acknowledgements

* fix condition

* rm old

* add font build

* add xata

* update migrations

* improve status badge, improve prompt

* rename

* update tracking

* versions

* only show placeholder on first item

* show not in scope items

* update link

* print poending status

* rm scaling

* conditional modal cta

* update prompt

* use unique stakeholders, textarea

* try fix borrow mut

* cache .riv

* add log

* Revert "try fix borrow mut"

This reverts commit 0915e937dfc64416480af4d5e83b3d2ec6a71d96.

* Reapply "try fix borrow mut"

This reverts commit 064bc1956f80eac40d69d0e035c4ab838b77bcbf.

* fix tracking conflict

* rm xata

* add deploy wf